# netlify.toml (MINIMAL TEST VERSION)

[build]
  command = "npm run build" # Or your actual build command
  publish = "dist"          # Or your actual publish directory (e.g., "build")

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200