# The corrected and final netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # --- THIS IS THE FINAL FIX ---
  # This line tells Netlify to include your secure articles in the deployment.
  included_files = ["_secure_content/**"]

# This "catch-all" redirect is for your React app.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200