[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; \
      script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; \
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; \
      font-src 'self' https://fonts.gstatic.com; \
      img-src 'self' data: https://www.google-analytics.com https://api.web3modal.org https://*.walletconnect.com; \
      connect-src 'self' https://polygon-mainnet.g.alchemy.com https://www.google-analytics.com https://*.walletconnect.com wss://*.walletconnect.com https://api.web3modal.org; \
      frame-src 'self' https://verify.walletconnect.com https://secure.walletconnect.com https://secure-mobile.walletconnect.com;"
    # Add any other headers you need on separate lines here
    # Example:
    # X-Frame-Options = "DENY"