[[headers]]
  for = "/*"
  [headers.values]
    X-Netlify-Test-Header = "ThisIsMyTest" # Keep this for now to confirm headers are still working
    Content-Security-Policy = "default-src 'self'; frame-ancestors 'self' https://secure.walletconnect.org https://verify.walletconnect.com;"