[[headers]]
  for = "/*"
  [headers.values]
    # Keep your other directives (default-src, script-src, etc.)
    Content-Security-Policy = """default-src 'self'; \
      script-src 'self' 'unsafe-inline' ... ; \
      style-src 'self' 'unsafe-inline' ... ; \
      img-src 'self' data: blob: ... ; \
      connect-src 'self' ... ; \
      frame-src 'self' https://verify.walletconnect.com https://secure.walletconnect.com https://secure-mobile.walletconnect.com https://*.walletconnect.org; \
      frame-ancestors 'self' https://secure.walletconnect.org;""" 
      # ^^^ TRY JUST THIS for frame-ancestors initially