[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self'; \
      script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://ssl.google-analytics.com; \
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; \
      font-src 'self' https://fonts.gstatic.com; \
      img-src 'self' data: blob: https://*.walletconnect.com https://*.walletconnect.org wss: https:; \
      connect-src 'self' https: wss:; \
      frame-src 'self' https://verify.walletconnect.com https://*.walletconnect.com https://*.walletconnect.org; \
      frame-ancestors 'self' http://localhost:* https://*.walletconnect.com https://*.walletconnect.org;
    """