      [headers.values]
        Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.web3modal.com https://www.google-analytics.com;"
        Permissions-Policy = "clipboard-read=(), clipboard-write=()"