# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

# If you want your headers back, add them here, otherwise this is the minimal version:
# [[headers]]
#  for = "/*"
#  [headers.values]
#    Content-Security-Policy = "..."
#    Permissions-Policy = "..."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200