[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """default-src 'self'; \
      script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://ssl.google-analytics.com; \
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; \
      font-src 'self' https://fonts.gstatic.com; \
      img-src 'self' data: blob: https://www.google-analytics.com https://api.web3modal.org https://*.walletconnect.com https://*.walletconnect.org https://cdn.zerion.io; \
      connect-src 'self' https://polygon-mainnet.g.alchemy.com https://www.google-analytics.com https://*.walletconnect.com https://*.walletconnect.org wss://*.walletconnect.com wss://*.walletconnect.org https://api.web3modal.org https://rpc.walletconnect.com; \
      frame-src 'self' https://verify.walletconnect.com https://secure.walletconnect.com https://secure-mobile.walletconnect.com https://secure.walletconnect.org https://*.walletconnect.org; \
      frame-ancestors 'self' http://localhost:* https://*.pages.dev https://*.vercel.app https://*.ngrok-free.app https://verify.walletconnect.com https://secure.walletconnect.com https://secure-mobile.walletconnect.com https://secure-mobile.walletconnect.org https://*.walletconnect.org;"""