# netlify.toml (MINIMAL TEST VERSION)

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions/"
  environment = { NODE_VERSION = "20" } # Or your preferred Node version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200