[[headers]]
  for = "/*"
  [headers.values]
    # Content-Security-Policy = """...your policy..."""
    # Add any OTHER headers you need here, like X-Frame-Options, etc.
    # For example:
    # X-Content-Type-Options = "nosniff"